### PR TITLE
Update bbmustache to version 1.12.2

### PR DESCRIPTION
**Pull request by benbro**

### CODE REVIEW

**Comment by benbro** [comment]
Fix for https://github.com/lrascao/rebar3_appup_plugin/issues/71

**Comment by lrascao** [comment]
> Fix for #71

wish we had GHA running here, were the tests sucessful?

**Comment by benbro** [comment]
I was able to compile my project.

**Comment by benbro** [comment]
Is there anything you want me to test?

**Comment by lrascao** [comment]
> Is there anything you want me to test?

if you're up for it would be cool to get github actions working here, tried to set them up but ran out of time

**Comment by benbro** [comment]
I don't know anything about github actions. Is there a way to run the tests locally for this PR?

**Comment by lrascao** [comment]
`make test`

**Comment by benbro** [comment]
I've installed otp 27.0.1 and run ```make test```.
I'm getting getting ```{badmatch,{error,1}``` for all tests. Example:
```erlang
%%% rebar3_appup_plugin_SUITE ==> generate.empty_appup: FAILED
%%% rebar3_appup_plugin_SUITE ==> {{badmatch,{error,1}},
 [{rebar3_appup_plugin_SUITE,upgrade_downgrade,6,
                             [{file,"/home/me/rebar3_appup_plugin/test/rebar3_appup_plugin_SUITE.erl"},
                              {line,816}]},
  {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1794}]},
  {test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1303}]},
  {test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,1235}]}]}
```

**Comment by benbro** [comment]
I'm getting the same errors with otp 26.2.5.2 and bbmustache  1.5.0.
The errors are not related to the otp or bbmustache version.

**Comment by lrascao** [comment]
yeah, tests might have broken for a while now, i'll try and pick it up when time permits, merging in the meantime

**Comment by benbro** [comment]
Is there a chance for a new release?

**Comment by lrascao** [comment]
> Can you please make a new release?

https://hex.pm/packages/rebar3_appup_plugin/2.4.6 has been cut

**Comment by benbro** [comment]
Thanks!

**Pull request merged**
