### PR TITLE
Replace deprecated string:tokens/2 and string:strip/3

### PR DESCRIPTION
**Pull request by benbro**
Replace deprecated string:tokens/2 and string:strip/3 with string:lexemes/2 and string:trim/3.

### CODE REVIEW

**Comment by lrascao** [comment]
it's failing on all other otp versions besides 20, we need to come up with a portable way of performing the same functionality

**Comment by ferd** [comment]
You might end up needing to take the approach we've taken for relx, rebar3, and erlware_commons and use optional compilation with a shim module or wrapper function.

**Comment by lrascao** [comment]
hope not, but yeah, it's an option

**Comment by benbro** [comment]
The old string functions will probably be supported.
Is it possible to keep using them and not fail on warnings?

**Comment by lrascao** [comment]
i'll take a look see first if there's another way of doing the same thing before dropping `warnings_as_errors`

**Comment by lrascao** [comment]
sorry, didn't mean to close this

**Comment by lrascao** [comment]
@benbro are you able to re-open it? i can't for some reason

**Comment by benbro** [comment]
I can't. The commit disappeared from my branch.

**Comment by lrascao** [comment]
damn, my bad, i fucked up with a force push, i'll open a new one with your changes and mine

**Pull request closed without merging**
